#!/bin/bash
# GO_Mac_Mod_ContraX_Brutal release-part lists (relative to GO_Mac_Mod_ContraX_Brutal/).
# Generated by assemble_mods.py - do not edit by hand.
# Rules: no overlap; config.json only in part 1; each zip stays under 2 GiB.

CONTRAX_BRUTAL_PART1=(
  "config.json"
  "GenArial.ttf"
  "Install_Final.bmp"
  "Data"
  "00_BossReplacer.big"
  "01_CameosHD.big"
  "02_ControlBarPro.big"
  "04_Patch1.big"
  "13_Textures.big"
  "16_Window.big"
)

CONTRAX_BRUTAL_PART2=(
  "03_DisableFogEffects.big"
  "05_AI.big"
  "06_Audio.big"
  "07_GameData.big"
  "09_INI.big"
  "11_MusicEnhanced.big"
)

CONTRAX_BRUTAL_PART3=(
  "08_HotkeysOriginal_English.big"
  "10_Maps.big"
  "12_Terrain.big"
  "14_UnitVoicesEnglish.big"
  "15_W3D.big"
)
