#!/bin/bash
# Shared ContraX release-part file lists (relative to GO_Mac_Mod_ContraX/).
# Generated by assemble_mods.py - do not edit by hand.
# Rules: no overlap; config.json only in part 1; each zip stays under 2 GiB.

CONTRAX_PART1=(
  00_CameosHD.big
  01_ControlBarPro.big
  03_Patch1.big
  12_Textures.big
  15_Window.big
  GenArial.ttf
  Install_Final.bmp
  config.json
)

CONTRAX_PART2=(
  02_DisableFogEffects.big
  04_AI.big
  05_Audio.big
  06_GameData.big
  08_INI.big
  10_MusicEnhanced.big
)

CONTRAX_PART3=(
  07_HotkeysOriginal_English.big
  09_Maps.big
  11_Terrain.big
  13_UnitVoicesEnglish.big
  14_W3D.big
)
