#!/bin/bash
# GO_Mac_Mod_Silent_Death release-part lists (relative to GO_Mac_Mod_Silent_Death/).
# Generated by assemble_mods.py - do not edit by hand.
# Rules: no overlap; config.json only in part 1; each zip stays under 2 GiB.

SILENT_DEATH_PART1=(
  "config.json"
  "Install_Final.bmp"
  "LSFkrInfEngineer.dds"
  "Data"
  "Maps"
  "Window"
)

SILENT_DEATH_PART2=(
  "!00EgyPatch.big"
  "00LSF0118.big"
  "Art/Terrain"
)

SILENT_DEATH_PART3=(
  "Art/Textures"
)

SILENT_DEATH_PART4=(
  "Art/W3D"
)
