#!/bin/bash
# GO_Mac_Mod_WW3 release-part lists (relative to GO_Mac_Mod_WW3/).
# Generated by assemble_mods.py - do not edit by hand.
# Rules: no overlap; config.json only in part 1; each zip stays under 2 GiB.

WW3_PART1=(
  "config.json"
  "Install_Final.bmp"
  "00_ControlBarPro1080ZH.big"
  "01_ControlBarProArt1080ZH.big"
  "02_ControlBarProData1080ZH.big"
  "03_ControlBarProZH.big"
  "04_PMBeta993.big"
)

WW3_PART2=(
  "06_PMBeta995.big"
  "07_PMBeta996.big"
  "08_PMBeta997.big"
  "09_PMBeta998.big"
  "10_PMBeta999.big"
)

WW3_PART3=(
  "05_PMBeta994.big"
  "Art"
  "Data"
  "Maps"
  "Window"
)
