FXList WeaponFX_GattlingCannonGunFireTracerRemiel
  Tracer
    TracerName = QuadCannonBulletTracer
    Speed = 400
    DecayAt = 1.1
  End
  LightPulse
    Color = R:255 G:255 B:128
    Radius = 20
    IncreaseTime = 50
    DecreaseTime = 100
  End
  ParticleSystem
    Name = HighCaliberCannonFiring
    Offset = X:1 Y:0 Z:0
    OrientToObject = Yes
  End
  ParticleSystem
    Name = MachinegunTinyLight
    OrientToObject = Yes
    Offset = X:1.0 Y:0.0 Z:2.0
  End
  ParticleSystem
    Name = HighCaliberCannonSmoke
    Offset = X:1 Y:0 Z:0
  End
  ParticleSystem
    Name = FallingShellsGattlingTilted
    OrientToObject = Yes
    Offset = X:0.0 Y:0.0 Z:0.0
  End
  ParticleSystem
    Name = HeavyRiflesFlare
    OrientToObject = Yes
  End
  Sound
    Name = SpectreGunshipGattlingWeapon
  End
End

FXList WeaponFX_RemielAGL
  Sound
    Name = AGLFireSound
  End
End

ObjectCreationList OCL_WuldorDeathEffect
  CreateObject
    ObjectNames = DeadWuldorHulk
    Count = 1
    Disposition = LIKE_EXISTING INHERIT_VELOCITY
  End
  CreateDebris
    ModelNames = AVScrap2 AVScrap3 AVScrap4 AVScrap5
    Count = 4
    Mass = 5.0
    Disposition = SEND_IT_FLYING
    DispositionIntensity = .5
  End
End

ObjectCreationList OCL_WuldorDeathEffectSimple
  CreateObject
    ObjectNames = DeadWuldorHulk
    Count = 1
    Disposition = LIKE_EXISTING INHERIT_VELOCITY
  End
End

ObjectCreationList OCL_UpgradeViaRiderSwitch1_Widow
  CreateObject
    ObjectNames = UpgradeViaRiderSwitch1_Widow
    ContainInsideSourceObject = Yes
    InheritsVeterancy = Yes
    IgnorePrimaryObstacle = Yes
  End
End

ObjectCreationList OCL_UpgradeViaRiderSwitch2_Widow
  CreateObject
    ObjectNames = UpgradeViaRiderSwitch2_Widow
    ContainInsideSourceObject = Yes
    InheritsVeterancy = Yes
    IgnorePrimaryObstacle = Yes
  End
End

ObjectCreationList OCL_UpgradeViaRiderSwitch3_Widow
  CreateObject
    ObjectNames = UpgradeViaRiderSwitch3_Widow
    ContainInsideSourceObject = Yes
    InheritsVeterancy = Yes
    IgnorePrimaryObstacle = Yes
  End
End

ObjectCreationList OCL_UpgradeViaRiderSwitch4_Widow
  CreateObject
    ObjectNames = UpgradeViaRiderSwitch4_Widow
    ContainInsideSourceObject = Yes
    InheritsVeterancy = Yes
    IgnorePrimaryObstacle = Yes
  End
End

ObjectCreationList OCL_UpgradeViaRiderSwitch5_Widow
  CreateObject
    ObjectNames = UpgradeViaRiderSwitch5_Widow
    ContainInsideSourceObject = Yes
    InheritsVeterancy = Yes
    IgnorePrimaryObstacle = Yes
  End
End

Weapon BossStingerMissileWeaponAir
  PrimaryDamage = 50.0
  PrimaryDamageRadius = 10.0
  AttackRange = 225.0
  DamageType = EXPLOSION
  DeathType = EXPLODED
  WeaponSpeed = 300
  ProjectileObject = BossStingerMissileAA
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 0
  ClipSize = 1
  ClipReloadTime = 3000
  AutoReloadsClip = Yes
  FireFX = FX_ChemStingerMissileIgnition
  FireSound = StingerMissileWeapon
;  ProjectileDetonationFX = WeaponFX_ChemStingerMissileDetonation
  AntiAirborneVehicle = Yes
  AntiAirborneInfantry = Yes
  AntiGround = No
  MissileCallsOnDie = Yes
  WeaponBonus = PLAYER_UPGRADE DAMAGE 125% ; AP rocket upgrade
End

Weapon SeraphMissileAntiInfantryDamage
  PrimaryDamage = 50.0
  PrimaryDamageRadius = 15.0
  SecondaryDamage = 15.0
  SecondaryDamageRadius = 35.0
  DamageType = SNIPER
  DeathType = EXPLODED
  DamageDealtAtSelfPosition = Yes
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
End

Weapon ToxoWagonSprayerUpgraded
  PrimaryDamage = 30
  PrimaryDamageRadius = 10.0
  AttackRange = 120.0
  DamageType = MICROWAVE
  DeathType = EXTRA_6
  WeaponSpeed = 250
  ProjectileObject = AcidTankStreamProjectileUpgraded
  FireFX = WeaponFX_AcidTankFlameWeaponUpgraded
  ProjectileDetonationFX = WeaponFX_AcidTankMissileDetonationUpgraded
  FireSound = ToxinTractorWeaponLoop
  FireSoundLoopTime = 80
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 50
  ClipSize = 30
  ClipReloadTime = 50
  ProjectileStreamName = AcidTankProjectileStreamUpgraded
  ProjectileCollidesWith = STRUCTURES
  AllowAttackGarrisonedBldgs = Yes
End

Weapon ToxoWagonToxinSprayerUpgraded
  PrimaryDamage = 12
  PrimaryDamageRadius = 15.0
  AttackRange = 140.0
  DamageType = POISON
  DeathType = POISONED_BETA
  WeaponSpeed = 300
  ProjectileObject = ToxinTruckStreamProjectileUpgraded
  FireFX = WeaponFX_ToxinTruckFlameWeaponUpgraded
  ProjectileDetonationFX = WeaponFX_ToxinTruckMissileDetonationUpgraded
  FireSound = ToxinTractorWeaponLoop
  FireSoundLoopTime = 80
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 40
  ClipSize = 30
  ClipReloadTime = 40
;  ProjectileStreamName = ToxinTruckProjectileStreamUpgraded
  ProjectileCollidesWith = STRUCTURES
  AllowAttackGarrisonedBldgs = Yes
End

Weapon ToxoWagonToxinSprayerGamma
  PrimaryDamage = 18
  PrimaryDamageRadius = 15.0
  AttackRange = 140.0
  DamageType = POISON
  DeathType = POISONED_GAMMA
  WeaponSpeed = 300
  ProjectileObject = GC_Chem_ToxinStreamProjectile
  FireFX = GC_Chem_WeaponFX_ToxinFlameWeaponGamma
  ProjectileDetonationFX = GC_Chem_WeaponFX_ToxinMissileDetonationGamma
  FireSound = ToxinTractorWeaponLoop
  FireSoundLoopTime = 80
  RadiusDamageAffects = ALLIES ENEMIES NEUTRALS
  DelayBetweenShots = 40
  ClipSize = 30
  ClipReloadTime = 40
;  ProjectileStreamName = GC_Chem_ToxinProjectileStream
  ProjectileCollidesWith = STRUCTURES
  AllowAttackGarrisonedBldgs = Yes
End

Weapon WidowInfantryRiderSwitch1ResetWeapon
  FireOCL = OCL_UpgradeViaRiderSwitch1_Widow
End

Weapon WidowInfantryRiderSwitch3ResetWeapon
  FireOCL = OCL_UpgradeViaRiderSwitch3_Widow
End

Weapon WidowInfantryRiderSwitch4ResetWeapon
  FireOCL = OCL_UpgradeViaRiderSwitch4_Widow
End

Weapon WidowInfantryRiderSwitch5ResetWeapon
  FireOCL = OCL_UpgradeViaRiderSwitch5_Widow
End
